NAME = "golang"
PORT = 8080
HOST = "0.0.0.0"
LOG = "./zap.log"


[MYSQL]
HOST = "10.24.100.111"
PORT = 3306
USER= "root"
PASSWORD = "123456"
DATABASE = "chat"
TABLEPREFIX = "chat_"

[REDIS]
HOST = "10.24.100.111"
PORT = 6379
PASSWORD = ""
DB = 0

[JWT]
ACCESSTOKEN = "token"
REFRESHTOKEN = "token"
SECRET = "will"
DURATION = 7200